# Generated by Django 4.0.6 on 2022-10-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascrap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arbitrage_master',
        ),
    ]
