# Generated by Django 4.0.6 on 2022-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascrap', '0002_delete_arbitrage_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitrage_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField()),
                ('today_time', models.TimeField()),
                ('matchtime', models.TextField()),
                ('sports_name', models.TextField()),
                ('team1_name', models.TextField()),
                ('team2_name', models.TextField()),
                ('team1_odds', models.TextField(default=None, null=True)),
                ('team2_odds', models.TextField(default=None, null=True)),
                ('stake1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stake2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profitper', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'arbitrage_master',
                'db_table': 'arbitrage_master',
            },
        ),
    ]
